---
# Setup 45drives Package Repository
- include: install/repository.yml
  when:
    - not offline_install

- include: install/redhat.yml
  when:
    - ansible_facts['os_family'] == 'RedHat'

- include: install/ubuntu.yml
  when: 
    - ansible_facts['distribution'] == 'Ubuntu'


