---
- name: redhat family | install dependency
  package:
    name: "{{ item }}"
    state: "{{ (upgrade_samba_packages|bool) | ternary('latest','present') }}"
  register: result
  until: result is succeeded
  with_items: "{{ rhel_dependencies}}"
  when: ansible_facts['os_family'] == 'RedHat'

- name: debian family | install dependency
  package:
    name: "{{ item }}"
    state: "{{ (upgrade_samba_packages|bool) | ternary('latest','present') }}"
  register: result
  until: result is succeeded
  with_items: "{{ debian_dependencies}}"
  when: ansible_facts['os_family'] == 'Debian'