- name: setup 45drives repository
  block:
  - name: Configure 45Drives repository | Get repo setup script
    get_url:
      url: https://repo.45drives.com/setup
      dest: /tmp/setup

  - name: Configure 45Drives repository | Run repo setup script
    shell: bash /tmp/setup

  - name: Configure 45Drives repository | Remove repo setup script
    file:
      path: /tmp/setup
      state: absent

- name: setup ceph repository on redhat family OS
  when: ansible_facts['os_family'] == 'RedHat'
  block:
    - name: install yum plugin priorities
      package:
        name: yum-plugin-priorities
      register: result
      until: result is succeeded
      when: ansible_facts['distribution_major_version'] | int == 7
  
    - name: configure red hat ceph community repository stable key
      rpm_key:
        key: "{{ ceph_stable_key }}"
        state: present
      register: result
      until: result is succeeded

    - name: configure red hat ceph stable community repository
      yum_repository:
        name: ceph_stable
        description: Ceph Stable $basearch repo
        gpgcheck: yes
        state: present
        gpgkey: "{{ ceph_stable_key }}"
        baseurl: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}/el{{ ansible_facts['distribution_major_version'] }}/$basearch"
        file: ceph_stable
        priority: 2
      register: result
      until: result is succeeded

    - name: configure red hat ceph stable noarch community repository
      yum_repository:
        name: ceph_stable_noarch
        description: Ceph Stable noarch repo
        gpgcheck: yes
        state: present
        gpgkey: "{{ ceph_stable_key }}"
        baseurl: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}/el{{ ansible_facts['distribution_major_version'] }}/noarch"
        file: ceph_stable
        priority: 2
      register: result
      until: result is succeeded

- name: setup ceph repository on debian family OS
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: install dependencies for apt modules
      package:
        name: ['apt-transport-https', 'ca-certificates', 'gnupg', 'software-properties-common']
        update_cache: yes
      register: result
      until: result is succeeded

    - name: configure debian ceph community repository stable key
      apt_key:
        url: "{{ ceph_stable_key }}"
        state: present
      register: result
      until: result is succeeded

    - name: configure debian ceph stable community repository
      apt_repository:
        repo: "deb {{ ceph_stable_repo }} {{ ansible_facts['distribution_release'] }} main"
        state: present
        update_cache: yes

    - name: update apt cache if cache_valid_time has expired
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: result
      until: result is succeeded