---
- name: configure for cephfs as backend fs
  debug:
    msg: "configured cephfs as backend fs"

- name: configure_cephfs_backend | Create directory for samba shares
  shell: /usr/bin/cephfs-shell "mkdir -m 755 -p /fsgw"
  run_once: true
  delegate_to: "{{ groups[mon_group_name][0] }}"

- name: configure_cephfs_backend | Get samba secret for cephfs mount
  command: "ceph auth get-key client.samba"
  register: command_output_samba
  changed_when: false
  delegate_to: "{{ groups[mon_group_name][0] }}"

- name: configure_cephfs_backend | Set samba secret fact
  set_fact:
    cephfs_samba_secret: "{{ command_output_samba.stdout }}"

- name: configure_cephfs_backend | write ceph samba client secret
  copy:
    content: "{{ cephfs_samba_secret }}"
    dest: /etc/ceph/samba.secret
    force: yes
    group: ceph
    owner: ceph
    mode: "0600"

- name: mount_cephfs | create local directory for share mount
  file:
    path: "{{ shared_storage_mountpoint }}"
    owner: "root"
    group: "root"
    mode: '0775'
    state: directory
  run_once: true

- name: mount_cephfs | mount share
  mount:
    name: "{{ shared_storage_mountpoint }}"
    src: ":/fsgw"
    fstype: "ceph"
    opts: "name=samba,secretfile=/etc/ceph/samba.secret,_netdev,relatime"
    state: mounted