---
- name: configure for cephfs as backend fs
  debug:
    msg: "configured cephfs as backend fs"

- name: configure_cephfs_backend | Create directory for samba shares
  shell: /usr/bin/cephfs-shell "mkdir -m 755 -p /fsgw"
  run_once: true

- name: configure_cephfs_backend | Create samba cephx user
  ceph_key:
    name: "{{ item.name }}"
    state: present
    caps: "{{ item.caps }}"
    cluster: "ceph"
    secret: "{{ item.key | default('') }}"
  with_items: "{{ cephfs_samba_keyring }}"

- name: configure_cephfs_backend | Get samba secret for cephfs mount
  command: "ceph auth get-key client.samba"
  register: command_output_samba
  changed_when: false

- name: configure_cephfs_backend | Set samba secret fact
  set_fact:
    cephfs_samba_secret: "{{ command_output_samba.stdout }}"

- name: configure_cephfs_backend | write ceph samba client secret
  copy:
    content: "{{ cephfs_samba_secret }}"
    dest: /etc/ceph/samba.secret
    force: yes
    group: ceph
    owner: ceph
    mode: "0600"

- name: configure_cephfs_backend | Get samba keyring for rados locking
  command: "ceph auth get client.samba"
  register: samba_keyring
  changed_when: false

- name: configure_cephfs_backend | Write samba keyring
  copy:
    content: "{{ samba_keyring.stdout }}\n"
    dest: "/etc/ceph/ceph.client.samba.keyring"
    force: yes
    group: ceph
    owner: ceph
    mode: "0600"

- name: mount_cephfs | create local directory for share mount
  file:
    path: "{{ shared_storage_mountpoint }}"
    owner: "root"
    group: "root"
    mode: '0775'
    state: directory
  run_once: true

- name: mount_cephfs | mount share
  mount:
    name: "{{ shared_storage_mountpoint }}"
    src: ":/fsgw"
    fstype: "ceph"
    opts: "name=samba,secretfile=/etc/ceph/samba.secret,_netdev,relatime"
    state: mounted