[global]
fsid = 9eb1eef1-4da4-40ae-9243-255c08957a39
mon_initial_members = node1,node2,node3
mon_host = 192.168.98.36,192.168.98.37,192.168.98.38

public network = 192.168.0.0/16
cluster network = 192.168.0.0/16
auth_cluster required = cephx
auth_service required = cephx
auth_client required = cephx
ms_bind_ipv6 = False
ms_bind_ipv4 = True
# BEGIN RGW CONFIG FOR node1 #
[client.rgw.node1]
host = node1
rgw_frontends = "beast endpoint=0.0.0.0:8080"
keyring = /var/lib/ceph/radosgw/ceph-rgw.node1/keyring
# BEGIN RGW CONFIG FOR node1 #
