- name: setup 45drives repository
  block:
  - name: Configure 45Drives repository | Get repo setup script
    get_url:
      url: https://repo.45drives.com/setup
      dest: /tmp/setup

  - name: Configure 45Drives repository | Run repo setup script
    shell: bash /tmp/setup

  - name: Configure 45Drives repository | Remove repo setup script
    file:
      path: /tmp/setup
      state: absent