---
- name: configure_cephfs_backend | Fetch ceph.conf from a monitor
  fetch:
    src: /etc/ceph/ceph.conf
    dest: fetch/conf/
    flat: yes
  delegate_to: "{{ groups.mons[0] }}"

- name: configure_cephfs_backend | Copy ceph.conf to smb gateways
  copy:
    src: fetch/conf/ceph.conf
    dest: /etc/ceph/ceph.conf

- name: configure_cephfs_backend | Create samba cephx user
  ceph_key:
    name: "{{ item.name }}"
    state: present
    caps: "{{ item.caps }}"
    cluster: "ceph"
    secret: "{{ item.key | default('') }}"
  with_items: "{{ cephfs_samba_keyring }}"
  delegate_to: "{{ groups.mons[0] }}"

- name: configure_cephfs_backend | Get samba keyring for rados locking
  command: "ceph auth get {{ cephfs_samba_keyring[0].name }}"
  register: samba_keyring
  changed_when: false
  delegate_to: "{{ groups.mons[0] }}"

- name: configure_cephfs_backend | Write samba keyring
  copy:
    content: "{{ samba_keyring.stdout }}\n"
    dest: "/etc/ceph/ceph.{{ cephfs_samba_keyring[0].name }}.keyring"
    force: yes
    group: ceph
    owner: ceph
    mode: "0600"
