---
- include: firewall.yml

- include: create_ceph_keyring.yml
  when:
    - backend_filesystem == "cephfs"

- include: ctdb.yml
  when:
    - cluster_member | bool

- include: kerberos_init.yml
  when:
    - domain_member | bool
    - join_auth == "kerberos"

- include: domain_join.yml
  when:
    - domain_member | bool

- include: samba.yml
