---
- name: check if already joined
  command: /bin/bash -c "/usr/sbin/realm list"
  register: domain_check

- name: Skip domain join if already join
  debug:
    msg: "Already joined to {{ realm }}, skipping domain join"
  when: domain_check.stdout != ""

- name: Join domain if not already joined
  when: domain_check.stdout == ""
  block:
    - name: Configuring realmd.conf
      template:
        src: etc/realmd.conf.j2
        dest: /etc/realmd.conf
        owner: "root"
        group: "root"
        mode: 0644

    - name: Restart realmd service
      service:
        name: realmd
        state: restarted

    - name: Write /etc/krb5.conf
      template:
        src: etc/krb5.conf.j2
        dest: /etc/krb5.conf
        owner: "root"
        group: "root"
        mode: 0644

    - name: Write smb.conf for domain join
      template:
        src: etc/samba/smb.conf.j2
        dest: /etc/samba/smb.conf.tmp
        owner: "root"
        group: "root"
        mode: 0644

    - name: Write net realmd wrapper script
      template:
        src: usr/bin/net-realmd-wrapper
        dest: /usr/bin/net-realmd-wrapper
        owner: "root"
        group: "root"
        mode: 0755

    - name: Join domain via {{ join_method }} w. Kerberos Auth 
      command: /usr/sbin/realm join {{ realm }} --membership-software=samba
      throttle: 1
      when:
        - join_auth == 'kerberos'
        - domain_check.stdout == ""

    - name: join domain via {{ join_method }} w. password Auth
      expect:
        command: /usr/sbin/realm join {{ realm }} --membership-software=samba -U {{ join_user }}
        responses:
          Password for *: "{{ join_password }}"
      throttle: 1
      when:
        - join_auth == 'password'
        - domain_check.stdout == ""

    - name: remove temp smb.conf
      file:
        path: /etc/samba/smb.conf.tmp
        state: absent

    # authselect is responsible for configuring nsswitch.conf, realm uses this when joining the domain
    # authselect does not exist for debian derivatives, so nsswitch.conf is generated here
    - name: configure nsswitch.conf in Ubuntu
      template:
        src: etc/nsswitch.conf.j2
        dest: /etc/nsswitch.conf
        owner: "root"
        group: "root"
        mode: 0644
      when:
        - ansible_facts['os_family'] == 'Debian'

    - name: Flush sssd cache
      block: 
        - name: stop sssd
          service:
            name: sssd
            state: stopped

        - name: remove sssd cache
          command: rm -f /var/lib/sss/db/*
        
        - name: start sssd
          service:
            name: sssd
            state: started
      when:
        - join_method == 'sssd'

